### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by 19h** [alax/jsrp#1]
```
TypeError: Cannot read property 'toString' of undefined
at TransBuffer.toHex (http://127.0.0.1:3000/build/init.js:1074:25)
at TransBuffer.toBigInteger (http://127.0.0.1:3000/build/init.js:1079:30)
at http://127.0.0.1:3000/build/init.js:915:35 at Object.exports.randomBytes (http://127.0.0.1:3000/build/init.js:3805:21)
at SRP.a (http://127.0.0.1:3000/build/init.js:913:21)
at Client.init (http://127.0.0.1:3000/build/init.js:463:23)
...
```

Can't use your build. Is it broken?

The code in question effectively is this:

```
let srpclient = new jsrp.client();

srpclient.init({
    username: 'testUser',
    password: 'password123'
}, () => {
    srpclient.createVerifier((err, result) => {
        console.log(result.salt, result.verifier);
        this.io.emit('login', seed);
    });
});
```

---

It might be worth noting that a build through browserify works as expected.

**Comment by alax** [comment]
Oh! Sorry for the late reply. I must've missed this in my inbox. I'll take a look at it and get it fixed up.

**Comment by alax** [comment]
Should be fixed in 0.2.1 available on the releases page. Thanks!

**Comment by mrinalwahal** [comment]
This still doesn't work in the release `v0.2.4`.

Any solutions to this, @alax?
